import argparse
import json
import os
import re
import time
from pathlib import Path


CACHE_ROOT = Path(os.environ.get("AI_MODEL_CACHE", Path.home() / ".cache" / "viral-video-breakdown"))
MODELSCOPE_CACHE = CACHE_ROOT / "modelscope"
HF_HOME = CACHE_ROOT / "huggingface"

LOCAL_MODELS = {
    "sensevoice": Path(
        os.environ.get(
            "SENSEVOICE_MODEL_DIR",
            str(CACHE_ROOT / "manual-models" / "SenseVoiceSmall"),
        )
    ),
    "seaco": MODELSCOPE_CACHE
    / "models"
    / "iic"
    / "speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
    "paraformer": MODELSCOPE_CACHE
    / "models"
    / "iic"
    / "speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
    "vad": MODELSCOPE_CACHE
    / "models"
    / "iic"
    / "speech_fsmn_vad_zh-cn-16k-common-pytorch",
    "punc": MODELSCOPE_CACHE
    / "models"
    / "iic"
    / "punc_ct-transformer_cn-en-common-vocab471067-large",
    "spk": MODELSCOPE_CACHE
    / "models"
    / "iic"
    / "speech_campplus_sv_zh-cn_16k-common",
}


def configure_cache() -> None:
    MODELSCOPE_CACHE.mkdir(parents=True, exist_ok=True)
    HF_HOME.mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("MODELSCOPE_CACHE", str(MODELSCOPE_CACHE))
    os.environ.setdefault("HF_HOME", str(HF_HOME))
    os.environ.setdefault("HF_HUB_CACHE", str(HF_HOME / "hub"))


def ms_to_srt_time(ms: int) -> str:
    total = max(0, int(ms))
    hours = total // 3_600_000
    total %= 3_600_000
    minutes = total // 60_000
    total %= 60_000
    seconds = total // 1_000
    millis = total % 1_000
    return f"{hours:02}:{minutes:02}:{seconds:02},{millis:03}"


def ms_to_label(ms: int) -> str:
    total = max(0, int(ms)) // 1000
    minutes = total // 60
    seconds = total % 60
    return f"{minutes:02}:{seconds:02}"


def clean_text(text: str) -> str:
    text = re.sub(r"<\|[^|]+?\|>", "", text)
    text = text.replace("<unk>", "")
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[ ]+([,.;:!?，。！？、])", r"\1", text)
    return text.strip()


def merge_sentence_info(items: list[dict], max_gap_ms: int = 800) -> list[dict]:
    merged: list[dict] = []
    for item in items:
        text = clean_text(str(item.get("text", "")))
        if not text:
            continue
        start = int(item.get("start", 0))
        end = int(item.get("end", start))
        spk = item.get("spk")
        if (
            merged
            and merged[-1].get("spk") == spk
            and start - int(merged[-1]["end"]) <= max_gap_ms
        ):
            merged[-1]["text"] = clean_text(merged[-1]["text"] + text)
            merged[-1]["end"] = max(int(merged[-1]["end"]), end)
        else:
            merged.append({"start": start, "end": end, "spk": spk, "text": text})
    return merged


def write_outputs(result: list[dict], out_prefix: Path, mode: str, elapsed: float) -> None:
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    json_path = out_prefix.with_suffix(".json")
    md_path = out_prefix.with_suffix(".md")
    srt_path = out_prefix.with_suffix(".srt")

    json_path.write_text(
        json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    item = result[0] if result else {}
    sentence_info = item.get("sentence_info") or []
    full_text = clean_text(str(item.get("text", "")))

    lines = [
        f"# FunASR transcript ({mode})",
        "",
        f"> Generated by run_funasr_asr.py. Elapsed: {elapsed:.2f}s. Not human-corrected.",
        "",
    ]

    srt_entries: list[str] = []
    if sentence_info:
        merged = merge_sentence_info(sentence_info)
        for index, seg in enumerate(merged, start=1):
            speaker = (
                f"SPEAKER_{int(seg['spk'])}" if seg.get("spk") is not None else "ASR"
            )
            start = int(seg["start"])
            end = int(seg["end"])
            text = clean_text(seg["text"])
            lines.append(f"- [{ms_to_label(start)}-{ms_to_label(end)}] {speaker}: {text}")
            srt_entries.append(
                "\n".join(
                    [
                        str(index),
                        f"{ms_to_srt_time(start)} --> {ms_to_srt_time(end)}",
                        f"{speaker}: {text}",
                        "",
                    ]
                )
            )
    elif full_text:
        lines.append(full_text)
    else:
        lines.append("[empty ASR result]")

    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    srt_path.write_text("\n".join(srt_entries), encoding="utf-8")


def build_model(mode: str, device: str):
    configure_cache()
    from funasr import AutoModel

    common = {"device": device, "disable_update": True}
    vad = str(LOCAL_MODELS["vad"]) if LOCAL_MODELS["vad"].exists() else "fsmn-vad"
    punc = str(LOCAL_MODELS["punc"]) if LOCAL_MODELS["punc"].exists() else "ct-punc"
    spk = str(LOCAL_MODELS["spk"]) if LOCAL_MODELS["spk"].exists() else "cam++"

    if mode == "seaco":
        model = str(LOCAL_MODELS["seaco"]) if LOCAL_MODELS["seaco"].exists() else "paraformer-zh"
        return AutoModel(model=model, vad_model=vad, punc_model=punc, **common)
    if mode == "seaco_spk":
        model = str(LOCAL_MODELS["seaco"]) if LOCAL_MODELS["seaco"].exists() else "paraformer-zh"
        return AutoModel(model=model, vad_model=vad, punc_model=punc, spk_model=spk, **common)
    if mode == "paraformer":
        model = (
            str(LOCAL_MODELS["paraformer"])
            if (LOCAL_MODELS["paraformer"] / "model.pt").exists()
            else "paraformer"
        )
        return AutoModel(model=model, vad_model=vad, punc_model=punc, **common)
    if mode == "sensevoice":
        model = (
            str(LOCAL_MODELS["sensevoice"])
            if (LOCAL_MODELS["sensevoice"] / "model.pt").exists()
            else "iic/SenseVoiceSmall"
        )
        return AutoModel(model=model, vad_model=vad, **common)
    raise ValueError(f"Unsupported mode: {mode}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["seaco", "seaco_spk", "paraformer", "sensevoice"], required=True)
    parser.add_argument("--audio", default=os.environ.get("ASR_AUDIO"))
    parser.add_argument("--out-prefix", default=os.environ.get("ASR_OUT_PREFIX"))
    parser.add_argument("--device", default=os.environ.get("ASR_DEVICE", "cuda:0"))
    parser.add_argument("--batch-size-s", type=int, default=300)
    parser.add_argument("--merge-vad", action="store_true")
    parser.add_argument("--merge-length-s", type=int, default=15)
    args = parser.parse_args()

    if not args.audio:
        raise SystemExit("Missing --audio or ASR_AUDIO")
    if not args.out_prefix:
        raise SystemExit("Missing --out-prefix or ASR_OUT_PREFIX")

    audio = Path(args.audio)
    out_prefix = Path(args.out_prefix)

    start = time.time()
    model = build_model(args.mode, args.device)
    generate_kwargs = {"input": str(audio), "batch_size_s": args.batch_size_s}
    if args.mode == "sensevoice":
        generate_kwargs.update({"language": "zh", "use_itn": True})
        if args.merge_vad:
            generate_kwargs.update(
                {"merge_vad": True, "merge_length_s": args.merge_length_s}
            )
    result = model.generate(**generate_kwargs)
    elapsed = time.time() - start
    write_outputs(result, out_prefix, args.mode, elapsed)
    print(f"wrote {out_prefix.with_suffix('.md')}")
    print(f"elapsed_sec {elapsed:.2f}")


if __name__ == "__main__":
    main()
